<?php

namespace Multoo\Shipping;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-21 at 15:21:30.
 */
class AbstractContactTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var AbstractContact
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = $this->getMockForAbstractClass('Multoo\Shipping\AbstractContact');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Multoo\Shipping\AbstractContact::setId
     */
    public function testSetId()
    {
        $value = 'tested';
        $this->object->setId($value);
        $this->assertEquals($value, $this->object->id);
    }

    /**
     * @covers Multoo\Shipping\AbstractContact::setCompanyName
     */
    public function testSetCompanyName()
    {
        $value = 'tested';
        $this->object->setCompanyName($value);
        $this->assertEquals($value, $this->object->companyName);
    }

    /**
     * @covers Multoo\Shipping\AbstractContact::setContactName
     */
    public function testSetContactName()
    {
        $value = 'tested';
        $this->object->setContactName($value);
        $this->assertEquals($value, $this->object->contactName);
    }

    /**
     * @covers Multoo\Shipping\AbstractContact::setAddress
     */
    public function testSetAddress()
    {
        $value = 'tested';
        $this->object->setAddress($value);
        $this->assertEquals($value, $this->object->address);
    }

    /**
     * @covers Multoo\Shipping\AbstractContact::setCityName
     */
    public function testSetCityName()
    {
        $value = 'tested';
        $this->object->setCityName($value);
        $this->assertEquals($value, $this->object->cityName);
    }

    /**
     * @covers Multoo\Shipping\AbstractContact::setZipCode
     */
    public function testSetZipCode()
    {
        $value = 'tested';
        $this->object->setZipCode($value);
        $this->assertEquals($value, $this->object->zipCode);
    }

    /**
     * @covers Multoo\Shipping\AbstractContact::setIsoCountryCode
     */
    public function testSetIsoCountryCode()
    {
        $value = 'tested';
        $this->object->setIsoCountryCode($value);
        $this->assertEquals($value, $this->object->isoCountryCode);
    }

    /**
     * @covers Multoo\Shipping\AbstractContact::setPhone
     */
    public function testSetPhone()
    {
        $value = 'tested';
        $this->object->setPhone($value);
        $this->assertEquals($value, $this->object->phone);
    }

    /**
     * @covers Multoo\Shipping\AbstractContact::setEmail
     */
    public function testSetEmail()
    {
        $value = 'tested';
        $this->object->setEmail($value);
        $this->assertEquals($value, $this->object->email);
    }
}
