<?php

namespace Multoo\Shipping;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-20 at 11:42:50.
 */
class ShippingFactoryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var ShippingFactory
     */
    protected $object;
    protected $injectorMock;

    /**
     * @covers Multoo\Shipping\ShippingFactory::__construct
     */
    protected function setUp()
    {
        $this->injectorMock = $this->getMockBuilder('Auryn\Provider')
            ->disableOriginalConstructor()
            ->getMock();
        $this->object = new ShippingFactory($this->injectorMock);
    }

    protected function tearDown()
    {
        
    }

    /**
     * @covers Multoo\Shipping\ShippingFactory::create
     */
    public function testCreate()
    {
        $batchObject = new \StdClass();

        $this->injectorMock->expects($this->once())
            ->method('make')
            ->will($this->returnValue($batchObject));

        $result = $this->object->create();

        $this->assertEquals($batchObject, $result);
    }
}
