<?php

namespace Multoo\Shipping;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-20 at 11:42:50.
 */
class ShippingFactoryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var ShippingFactory
     */
    protected $object;

    /**
     * @covers Multoo\Shipping\ShippingFactory::__construct
     */
    protected function setUp()
    {
        $this->object = new ShippingFactory();
    }

    protected function tearDown()
    {
        
    }

    /**
     * @covers Multoo\Shipping\ShippingFactory::create
     */
    public function testCreate()
    {
        $result = $this->object->create();
        $this->assertInstanceOf('\Multoo\Shipping\Batch', $result);
    }
}
