<?php

namespace Multoo\Shipping;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-21 at 15:19:30.
 */
class ShipperTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Shipper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Shipper;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Multoo\Shipping\Shipper::setIata
     */
    public function testSetIata()
    {
        $value = 'tested';
        $this->object->setIata($value);
        $this->assertEquals($value, $this->object->iata);
    }
}
