<?php

namespace Multoo\Shipping\Provider;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-20 at 11:42:50.
 */
class ProviderFactoryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var ProviderFactory
     */
    protected $object;

    protected function setUp()
    {
        $this->object = new ProviderFactory();
    }

    protected function tearDown()
    {
        
    }

    /**
     * @covers Multoo\Shipping\Provider\ProviderFactory::create
     */
    public function testCreateUps()
    {

        $result = $this->object->create('ups');
        $this->assertInstanceOf('\Multoo\Shipping\Provider\Ups', $result);

    }
    
    /**
     * @covers Multoo\Shipping\Provider\ProviderFactory::create
     */
    public function testCreateDhl()
    {

        $result = $this->object->create('dhl');
        $this->assertInstanceOf('\Multoo\Shipping\Provider\Dhl', $result);

    }
}
