<?php

namespace Multoo\Shipping\Provider;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-20 at 11:42:57.
 */
class UpsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Ups
     */
    protected $object;

    /**
     * @covers Multoo\Shipping\Provider\Ups::__construct
     */
    protected function setUp()
    {

        $this->object = new Ups;
    }

    protected function tearDown()
    {
        
    }

    /**
     * @covers Multoo\Shipping\Provider\AbstractProvider::build
     * @covers Multoo\Shipping\Provider\Ups::processOutput
     * @covers Multoo\Shipping\Provider\Ups::processDepartureShipment
     * @covers Multoo\Shipping\Provider\Ups::processReturnShipment
     * @covers Multoo\Shipping\Provider\Ups::processShipmentBasics
     * @covers Multoo\Shipping\Provider\Ups::processReceiverOrShipper
     * @covers Multoo\Shipping\Provider\Ups::processPackages
     * @covers Multoo\Shipping\Provider\Ups::processNotiRecipients
     */
    public function testBuild()
    {

        $actual = $this->object->build(new \UpsBatchFixture);

        $expected = <<<'EOD'
<?xml version="1.0" encoding="UTF-8"?>
    <Shipments xmlns="http://www.ups.com/XMLSchema/CT/WorldShip/ImpExp/ShipmentImport/v1_0_0">
        <Shipment>
          <ShipTo>
            <CustomerID>4654464</CustomerID>
            <CompanyOrName>Scheep BV</CompanyOrName>
            <Attention>Jan Jansen</Attention>
            <Address1>Street 1A</Address1>
            <CountryTerritory>NL</CountryTerritory>
            <PostalCode>1234AS</PostalCode>
            <CityOrTown>Somewhere</CityOrTown>
            <Telephone>0529485005</Telephone>
          </ShipTo>
          <ShipFrom>
            <CustomerID>12345678</CustomerID>
            <CompanyOrName>Test BV</CompanyOrName>
            <Attention>Alex Damen</Attention>
            <Address1>Westerveen 3A</Address1>
            <CountryTerritory>NL</CountryTerritory>
            <PostalCode>7711DA</PostalCode>
            <CityOrTown>Nieuwleusen</CityOrTown>
            <Telephone>0529484004</Telephone>
          </ShipFrom>
          <ShipmentInformation>
            <ShipperNumber>12345678</ShipperNumber>
            <ServiceType>ST</ServiceType>
            <BillingOption>PP</BillingOption>
            <NumberOfPackages>1</NumberOfPackages>
            <DescriptionOfGoods>shipment0-descriptionOfGoods</DescriptionOfGoods>
            <ShipmentOptions>
              <QVN>
                <Option>Y</Option>
                <ShipFromCompanyOrName>Test BV</ShipFromCompanyOrName>
                <FailedEmailAddress>shipment0@company.org</FailedEmailAddress>
                <IncludeDutiesAndTaxesInMemo>N</IncludeDutiesAndTaxesInMemo>
                <Recipients>
                  <Recipient1>
                    <CompanyOrName>Scheep BV</CompanyOrName>
                    <ContactName>Jan Jansen</ContactName>
                    <Email>Jan@Scheep.bv</Email>
                    <ShipOrReturnNotification>Y</ShipOrReturnNotification>
                    <InTransitNotification>Y</InTransitNotification>
                    <DeliveryNotification>Y</DeliveryNotification>
                  </Recipient1>
                </Recipients>
              </QVN>
            </ShipmentOptions>
          </ShipmentInformation>
          <Packages>
            <Package>
              <PackageType>CP</PackageType>
              <Weight>1.00</Weight>
              <ReferenceNumbers>
                <Reference1>p0-ref1</Reference1>
                <Reference2>p0-ref2</Reference2>
                <Reference3>p0-ref3</Reference3>
                <Reference4>p0-ref4</Reference4>
                <Reference5>p0-ref5</Reference5>
              </ReferenceNumbers>
            </Package>
          </Packages>
        </Shipment>
        <Shipment>
          <ShipTo>
            <CustomerID>4654464</CustomerID>
            <CompanyOrName>Scheep BV</CompanyOrName>
            <Attention>Jan Jansen</Attention>
            <Address1>Street 1A</Address1>
            <CountryTerritory>NL</CountryTerritory>
            <PostalCode>1234AS</PostalCode>
            <CityOrTown>Somewhere</CityOrTown>
            <Telephone>0529485005</Telephone>
          </ShipTo>
          <ShipFrom>
            <CustomerID>12345678</CustomerID>
            <CompanyOrName>Test BV</CompanyOrName>
            <Attention>Alex Damen</Attention>
            <Address1>Westerveen 3A</Address1>
            <CountryTerritory>NL</CountryTerritory>
            <PostalCode>7711DA</PostalCode>
            <CityOrTown>Nieuwleusen</CityOrTown>
            <Telephone>0529484004</Telephone>
          </ShipFrom>
          <ShipmentInformation>
            <ShipperNumber>12345678</ShipperNumber>
            <ServiceType>ST</ServiceType>
            <BillingOption>PP</BillingOption>
            <NumberOfPackages>1</NumberOfPackages>
            <DescriptionOfGoods>shipment0-descriptionOfGoods</DescriptionOfGoods>
            <ShipmentOptions>
              <QVN>
                <Option>Y</Option>
                <ShipFromCompanyOrName>Test BV</ShipFromCompanyOrName>
                <FailedEmailAddress>shipment0@company.org</FailedEmailAddress>
                <IncludeDutiesAndTaxesInMemo>N</IncludeDutiesAndTaxesInMemo>
                <Recipients>
                  <Recipient1>
                    <CompanyOrName>Pintip BV</CompanyOrName>
                    <ContactName>Bas Pintip</ContactName>
                    <Email>bas@pintip.nl</Email>
                    <ExceptionNotification>Y</ExceptionNotification>
                    <LabelCreationNotification>Y</LabelCreationNotification>
                  </Recipient1>
                </Recipients>
              </QVN>
              <ReturnService>
                <Option>Y</Option>
                <Type>PRL</Type>
                <MerchandiseDescription>shipment0-descriptionOfGoods</MerchandiseDescription>
              </ReturnService>
            </ShipmentOptions>
          </ShipmentInformation>
          <Packages>
            <Package>
              <PackageType>CP</PackageType>
              <Weight>1.00</Weight>
              <ReferenceNumbers>
                <Reference1>p0-ref1</Reference1>
                <Reference2>p0-ref2</Reference2>
                <Reference3>p0-ref3</Reference3>
                <Reference4>p0-ref4</Reference4>
                <Reference5>p0-ref5</Reference5>
              </ReferenceNumbers>
            </Package>
          </Packages>
        </Shipment>
        <Shipment>
          <ShipTo>
            <CustomerID>35354647</CustomerID>
            <CompanyOrName>Test BV</CompanyOrName>
            <Attention>Henk Tester</Attention>
            <Address1>Road 732-32</Address1>
            <CountryTerritory>NL</CountryTerritory>
            <PostalCode>1252HG</PostalCode>
            <CityOrTown>Overthere</CityOrTown>
            <Telephone>0529485007</Telephone>
          </ShipTo>
          <ShipFrom>
            <CustomerID>12345678</CustomerID>
            <CompanyOrName>Test BV</CompanyOrName>
            <Attention>Alex Damen</Attention>
            <Address1>Westerveen 3A</Address1>
            <CountryTerritory>NL</CountryTerritory>
            <PostalCode>7711DA</PostalCode>
            <CityOrTown>Nieuwleusen</CityOrTown>
            <Telephone>0529484004</Telephone>
          </ShipFrom>
          <ShipmentInformation>
            <ShipperNumber>12345678</ShipperNumber>
            <ServiceType>ST</ServiceType>
            <BillingOption>PP</BillingOption>
            <NumberOfPackages>2</NumberOfPackages>
            <DescriptionOfGoods>shipment1-descriptionOfGoods</DescriptionOfGoods>
          </ShipmentInformation>
          <Packages>
            <Package>
              <PackageType>CP</PackageType>
              <Weight>1.25</Weight>
            </Package>
            <Package>
              <PackageType>CP</PackageType>
              <Weight>1.25</Weight>
            </Package>
          </Packages>
        </Shipment>
        <Shipment>
          <ShipTo>
            <CustomerID>789342789</CustomerID>
            <CompanyOrName>Heb-ik-jouw-daar BV</CompanyOrName>
            <Attention>Jop Jansen</Attention>
            <Address1>Straat 19B</Address1>
            <CountryTerritory>NL</CountryTerritory>
            <PostalCode>9874KO</PostalCode>
            <CityOrTown>Dontknow</CityOrTown>
            <Telephone>0529485006</Telephone>
          </ShipTo>
          <ShipFrom>
            <CustomerID>12345678</CustomerID>
            <CompanyOrName>Test BV</CompanyOrName>
            <Attention>Alex Damen</Attention>
            <Address1>Westerveen 3A</Address1>
            <CountryTerritory>NL</CountryTerritory>
            <PostalCode>7711DA</PostalCode>
            <CityOrTown>Nieuwleusen</CityOrTown>
            <Telephone>0529484004</Telephone>
          </ShipFrom>
          <ShipmentInformation>
            <ShipperNumber>12345678</ShipperNumber>
            <ServiceType>ST</ServiceType>
            <BillingOption>PP</BillingOption>
            <NumberOfPackages>1</NumberOfPackages>
            <DescriptionOfGoods>shipment3-descriptionOfGoods</DescriptionOfGoods>
            <ShipmentOptions>
              <ReturnService>
                <Option>Y</Option>
                <Type>PRL</Type>
                <MerchandiseDescription>shipment3-descriptionOfGoods</MerchandiseDescription>
              </ReturnService>
            </ShipmentOptions>
          </ShipmentInformation>
          <Packages>
            <Package>
              <PackageType>CP</PackageType>
              <Weight>1.00</Weight>
              <ReferenceNumbers>
                <Reference1>p0-ref1</Reference1>
                <Reference2>p0-ref2</Reference2>
                <Reference3>p0-ref3</Reference3>
                <Reference4>p0-ref4</Reference4>
                <Reference5>p0-ref5</Reference5>
              </ReferenceNumbers>
            </Package>
          </Packages>
        </Shipment>
        <Shipment>
          <ShipTo>
            <CustomerID>789342789</CustomerID>
            <CompanyOrName>Heb-ik-jouw-daar BV</CompanyOrName>
            <Attention>Jop Jansen</Attention>
            <Address1>Straat 19B</Address1>
            <CountryTerritory>NL</CountryTerritory>
            <PostalCode>9874KO</PostalCode>
            <CityOrTown>Dontknow</CityOrTown>
            <Telephone>0529485006</Telephone>
          </ShipTo>
          <ShipFrom>
            <CustomerID>12345678</CustomerID>
            <CompanyOrName>Test BV</CompanyOrName>
            <Attention>Alex Damen</Attention>
            <Address1>Westerveen 3A</Address1>
            <CountryTerritory>NL</CountryTerritory>
            <PostalCode>7711DA</PostalCode>
            <CityOrTown>Nieuwleusen</CityOrTown>
            <Telephone>0529484004</Telephone>
          </ShipFrom>
          <ShipmentInformation>
            <ShipperNumber>12345678</ShipperNumber>
            <ServiceType>ST</ServiceType>
            <BillingOption>PP</BillingOption>
            <NumberOfPackages>1</NumberOfPackages>
            <DescriptionOfGoods>shipment3-descriptionOfGoods</DescriptionOfGoods>
            <ShipmentOptions>
              <ReturnService>
                <Option>Y</Option>
                <Type>PRL</Type>
                <MerchandiseDescription>shipment3-descriptionOfGoods</MerchandiseDescription>
              </ReturnService>
            </ShipmentOptions>
          </ShipmentInformation>
          <Packages>
            <Package>
              <PackageType>CP</PackageType>
              <Weight>2.25</Weight>
              <ReferenceNumbers>
                <Reference5>p2-ref5</Reference5>
              </ReferenceNumbers>
            </Package>
          </Packages>
        </Shipment>
        <Shipment>
          <ShipTo>
            <CustomerID>789342789</CustomerID>
            <CompanyOrName>Heb-ik-jouw-daar BV</CompanyOrName>
            <Attention>Jop Jansen</Attention>
            <Address1>Straat 19B</Address1>
            <CountryTerritory>NL</CountryTerritory>
            <PostalCode>9874KO</PostalCode>
            <CityOrTown>Dontknow</CityOrTown>
            <Telephone>0529485006</Telephone>
          </ShipTo>
          <ShipFrom>
            <CustomerID>12345678</CustomerID>
            <CompanyOrName>Test BV</CompanyOrName>
            <Attention>Alex Damen</Attention>
            <Address1>Westerveen 3A</Address1>
            <CountryTerritory>NL</CountryTerritory>
            <PostalCode>7711DA</PostalCode>
            <CityOrTown>Nieuwleusen</CityOrTown>
            <Telephone>0529484004</Telephone>
          </ShipFrom>
          <ShipmentInformation>
            <ShipperNumber>12345678</ShipperNumber>
            <ServiceType>ST</ServiceType>
            <BillingOption>PP</BillingOption>
            <NumberOfPackages>1</NumberOfPackages>
            <DescriptionOfGoods>shipment3-descriptionOfGoods</DescriptionOfGoods>
            <ShipmentOptions>
              <ReturnService>
                <Option>Y</Option>
                <Type>PRL</Type>
                <MerchandiseDescription>shipment3-descriptionOfGoods</MerchandiseDescription>
              </ReturnService>
            </ShipmentOptions>
          </ShipmentInformation>
          <Packages>
            <Package>
              <PackageType>CP</PackageType>
              <Weight>5.25</Weight>
              <ReferenceNumbers>
                <Reference1>p3-ref1</Reference1>
                <Reference2>p3-ref2</Reference2>
                <Reference3>p3-ref3</Reference3>
                <Reference4>p3-ref4</Reference4>
              </ReferenceNumbers>
            </Package>
          </Packages>
        </Shipment>
        <Shipment>
          <ShipTo>
            <CustomerID>789342789</CustomerID>
            <CompanyOrName>Heb-ik-jouw-daar BV</CompanyOrName>
            <Attention>Jop Jansen</Attention>
            <Address1>Straat 19B</Address1>
            <CountryTerritory>NL</CountryTerritory>
            <PostalCode>9874KO</PostalCode>
            <CityOrTown>Dontknow</CityOrTown>
            <Telephone>0529485006</Telephone>
          </ShipTo>
          <ShipFrom>
            <CustomerID>12345678</CustomerID>
            <CompanyOrName>Test BV</CompanyOrName>
            <Attention>Alex Damen</Attention>
            <Address1>Westerveen 3A</Address1>
            <CountryTerritory>NL</CountryTerritory>
            <PostalCode>7711DA</PostalCode>
            <CityOrTown>Nieuwleusen</CityOrTown>
            <Telephone>0529484004</Telephone>
          </ShipFrom>
          <ShipmentInformation>
            <ShipperNumber>12345678</ShipperNumber>
            <ServiceType>ST</ServiceType>
            <BillingOption>PP</BillingOption>
            <NumberOfPackages>1</NumberOfPackages>
            <DescriptionOfGoods>shipment3-descriptionOfGoods</DescriptionOfGoods>
            <ShipmentOptions>
              <ReturnService>
                <Option>Y</Option>
                <Type>PRL</Type>
                <MerchandiseDescription>shipment3-descriptionOfGoods</MerchandiseDescription>
              </ReturnService>
            </ShipmentOptions>
          </ShipmentInformation>
          <Packages>
            <Package>
              <PackageType>CP</PackageType>
              <Weight>3.25</Weight>
            </Package>
          </Packages>
        </Shipment>
    </Shipments>
EOD;

        $this->assertXmlStringEqualsXmlString($expected, $actual);
    }
}
